apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/QuintenBruynseraede/home-lab.git
    chart: grafana
  destination:
    namespace: grafana
  project: default